server:
  port: 8000
spring:
  jackson:
    #default-property-inclusion: ALWAYS, CUSTOM, NON_ABSENT, NON_DEFAULT, NON_EMPTY, NON_NULL, USE_DEFAULTS
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:mysql://localhost:3306/outhservice?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    show-sql: true

check-user-scopes: true
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO